version: '2'
services:
  dataintegration-app:
    image: dataintegration
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dataintegration-postgresql:5432/dataintegration
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  dataintegration-postgresql:
    extends:
      file: postgresql.yml
      service: dataintegration-postgresql
